### ISSUE TITLE
Serz.exe

### ISSUE THREAD

**Issue by Emretok0** [ElPerenza/VSCode-serz#3]
Error Code:
`Path "C:\Users\HP\.vscode\extensions\elperenza.vscode-serz-1.2.0\out\serz.exe" isn't a valid serz executable path (file does not exist).`

I can't find the serz.exe file , can you give it to me manually?
Thanks.

**Comment by ElPerenza** [comment]
serz.exe should be found in the root directory of your Train Simulator installation. I can't share the file as it would almost certainly break Train Simulator's EULA.
